发评论
stackshot/stackshot-api pull request #2
Opened 2016-10-30 11:27 UTC by ncysatnaf

@egoist  你觉得单接口多参数 和 多接口少参数哪个好？ 🙃

2016-11-01 13:09 UTC, egoist commented
啥意思。。

2016-11-01 13:14 UTC, egoist requested changes

2016-11-01 13:14 UTC, egoist commented on src/models/shot.js
> +  latestComment: [{
这是干啥的

2016-11-01 13:14 UTC, egoist commented on src/models/shot.js
> +  liked: {
这个 liked 是干嘛的，判断是否点赞应该是存在单独的一个 model 吧

2016-11-01 13:14 UTC, egoist commented on src/controllers/shot.js
> +    const shot = new Shot(shotData)
添加评论为什么是 Shot

2016-11-01 13:30 UTC, ncysatnaf commented on src/controllers/shot.js
> +    const shot = new Shot(shotData)
－点赞直接判断shot 里 likedUser的_id和当前匹不匹配 然后计算liked （点赞时插入）
－latestComment  列表请求时拿最新的几条评论
－shot 抽象成type：｛image, comment, ..... ｝ ，这个有点激进～
😥

2016-11-01 13:41 UTC, egoist commented on src/controllers/shot.js
> +    const shot = new Shot(shotData)
- liked 是 API 返回的时候计算的吧
- 评论单独放在一个 model

2016-11-01 13:43 UTC, egoist commented on src/controllers/shot.js
> +    const shot = new Shot(shotData)
没有人用截图来回复截图 😂

2016-11-01 13:46 UTC, ncysatnaf commented on src/controllers/shot.js
> +    const shot = new Shot(shotData)
- liked是返回时计算的  
- 好吧～

话说在mongodb里 两个model是不是就是两个collection？

2016-11-01 13:52 UTC, ncysatnaf commented on src/controllers/shot.js
> +    const shot = new Shot(shotData)
我把shot当成发射的意思了www
话说之前用的api就是这样干的 ，一个接口感觉用起来挺爽的说～～

2016-11-01 13:53 UTC, egoist requested changes

2016-11-01 13:53 UTC, egoist commented on src/models/shot.js
> +  liked: {
返回时计算那为什么 schema 里有 liked

2016-11-01 13:53 UTC, egoist commented on src/models/user.js
> +    type: Array
```js
[{
  type: Schema.Types.ObjectId,
  ref: 'Shot'
}]
```

2016-11-01 13:53 UTC, egoist commented on src/routers/private-router.js
> +router.put('/shot/:id', shot.PutShotById)
点赞单独放在

```js
router.put('/shot/:id/like', shot.PutShotById)
```

吧

2016-11-01 13:54 UTC, egoist commented on src/controllers/shot.js
> +    const shot = new Shot(shotData)
`Shot` 是截图...

2016-11-01 13:58 UTC, ncysatnaf commented on src/models/shot.js
> +  liked: {
😅

2016-11-01 14:01 UTC, ncysatnaf commented on src/models/user.js
> +    type: Array
之前push －f三次完了  还是有这么多问题😂

2016-11-01 15:16 UTC, ncysatnaf commented on src/models/shot.js
> +  liked: {
貌似schema里没有liked的话   计算的不生效。。   返回的数据里没有liked    是我的姿势有问题么～～

2016-11-01 15:17 UTC, egoist commented on src/routers/private-router.js
> +router.put('/shot/:id/like', shot.LikeShotById)
```diff
-LikeShotById
+likeShotById
```
😂

2016-11-01 15:22 UTC, uu-z commented on src/routers/private-router.js
> +router.put('/shot/:id/like', shot.LikeShotById)
😅

2016-11-01 15:25 UTC, egoist commented on src/models/shot.js
> +  liked: {
http://stackoverflow.com/questions/14504385/why-cant-you-modify-the-data-returned-by-a-mongoose-query-ex-findbyid

2016-11-02 02:03 UTC, ncysatnaf commented on src/models/shot.js
> +  liked: {
len()和 toObject()/toJson() 用起来有点不友好， 
直接在shot._doc 上塞了一条～ 😂
http://stackoverflow.com/questions/18821212/mongoose-whats-up-with-doc

2016-11-05 02:07 UTC, ncysatnaf commented
@egoist  可不可以合并呀～😂

2016-11-05 02:54 UTC, egoist requested changes

2016-11-05 02:54 UTC, egoist commented on docs/comment.md
> +|parent|string|✅|评论目标(shot_id)|
parent 改成 shot 吧

2016-11-06 13:15 UTC, egoist commented on docs/comment.md
> +  "shot": shotSchema,
添加评论干嘛返回 shot

2016-11-06 13:15 UTC, egoist commented on docs/like.md
> +  "user": userSchema
只用返回新的 liked 结果

2016-11-06 13:30 UTC, merged

2016-11-07 00:35 UTC, ncysatnaf commented on docs/comment.md
> +  "shot": shotSchema,
因为react native这边用的normalizr  处理数据是以schema为单位的 
唔 简单点就是   用返回的shot  merge更新被更新的shot   
liked也是同理

2016-11-07 01:24 UTC, ncysatnaf commented on docs/like.md
> +  "user": userSchema
这里好像确实是不用返回user

2016-11-07 03:24 UTC, uu-z reviewed
latestComment你有比较好的实现方法没，  我是想放在shot里面...